In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat
import seaborn as sb
from mlxtend.plotting import plot_decision_regions
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,accuracy_score

In [3]:

df=pd.DataFrame(pd.read_csv("E:\\Study\\AIDS\\DS\\ML\\placement.csv"))
df.head()

cgpa   iq  placement
0   6.8  123          1
1   5.9  106          0
2   5.3  121          0
3   7.4  132          1
4   5.8  142          0

In [4]:
df.drop(columns="iq",inplace=True)
df.head()

cgpa  placement
0   6.8          1
1   5.9          0
2   5.3          0
3   7.4          1
4   5.8          0

In [5]:
df.isnull().sum()

cgpa         0
placement    0
dtype: int64

In [6]:
df

cgpa  placement
0    6.8          1
1    5.9          0
2    5.3          0
3    7.4          1
4    5.8          0
..   ...        ...
95   4.3          0
96   4.4          0
97   6.7          1
98   6.3          1
99   6.2          1

[100 rows x 2 columns]

In [7]:
newd=df.head(10)
newd

cgpa  placement
0   6.8          1
1   5.9          0
2   5.3          0
3   7.4          1
4   5.8          0
5   7.1          1
6   5.7          0
7   5.0          0
8   6.1          0
9   5.1          0

In [8]:
x=newd["cgpa"]
y=newd["placement"]

In [9]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

In [13]:
lo=LeaveOneOut()
for train ,test in lo.split(x,y):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [15]:
lo=LeavePOut(p=2)
for train ,test in lo.split(x,y):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [16]:
lo=KFold(n_splits=5)
for train ,test in lo.split(x,y):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [23]:
x=newd[["cgpa"]]
y=newd["placement"]


In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression


In [28]:
cross_val_score(LinearRegression(),x,y,cv=5)

array([0.65512588, 0.98093063, 0.85829174, 0.        , 0.        ])